### PR TITLE
Fixed where trying to mutate a non-existent value on null type clauses

### PR DESCRIPTION
**Pull request by dlett**
Null type wheres do not have a value, and were throwing an undefined index exception.

### CODE REVIEW

**Review by mtrpcic — APPROVED** [review]

**Comment by mtrpcic** [comment]
I approved but I also have no idea what I'm doing.

**Comment by bryanashley** [comment]
I disagree.

**Comment by bryanashley** [comment]
Nah this makes sense, but can you add a test showing it failing beforehand? @dlett

**Comment by bryanashley** [comment]
Ah nevermind the builder class isnt tested at all, keep on livin your life.

**Pull request merged**
